/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
kango.WebProgressListener=function(callback){this._callback=callback;};kango.WebProgressListener.prototype={_callback:null,QueryInterface:function(aIID){if(aIID.equals(Components.interfaces.nsIWebProgressListener)||aIID.equals(Components.interfaces.nsISupportsWeakReference)||aIID.equals(Components.interfaces.nsISupports))
return this;throw Components.results.NS_NOINTERFACE;},onProgressChange:function(aWebProgress,aRequest,aCurSelfProgress,aMaxSelfProgress,aCurTotalProgress,aMaxTotalProgress){},onStatusChange:function(aWebProgress,aRequest,aStatus,aMessage){},onSecurityChange:function(aWebProgress,aRequest,aState){},onLocationChange:function(aProgress,aRequest,aLocation){},onStateChange:function(aWebProgress,aRequest,aStateFlags,aStatus){var nsIWebProgressListener=Components.interfaces.nsIWebProgressListener;if(aStateFlags&nsIWebProgressListener.STATE_START&&aStateFlags&nsIWebProgressListener.STATE_IS_DOCUMENT){var nsIChannel=Components.interfaces.nsIChannel;var event={url:aRequest.QueryInterface(nsIChannel).originalURI.spec,window:aWebProgress.DOMWindow,document:aWebProgress.DOMWindow.document};this._callback(event);}}};kango.Browser=function(){this.superclass.apply(this,arguments);this._lastTabId=0;this._webProgressListener=new kango.WebProgressListener(kango.lang.bind(this._onPageBeforeNavigate,this));kango.addEventListener(kango.event.Ready,kango.lang.bind(this._subscribeEvents,this));};kango.Browser.prototype=kango.oop.extend(kango.BrowserBase,{_webProgressListener:null,_lastTabId:0,_generateTabId:function(){return this._lastTabId++;},_subscribeEvents:function(){document.getElementById('appcontent').addEventListener('DOMContentLoaded',kango.lang.bind(this._onPageLoad,this),true);gBrowser.addProgressListener(this._webProgressListener);gBrowser.tabContainer.addEventListener('TabSelect',kango.lang.bind(this._onTabSelect,this),false);gBrowser.tabContainer.addEventListener('TabOpen',kango.lang.bind(this._onTabOpen,this),false);gBrowser.tabContainer.addEventListener('TabClose',kango.lang.bind(this._onTabClose,this),false);},_onPageBeforeNavigate:function(event){if(!event.document.defaultView.frameElement){var win=event.document.defaultView.top;this.fireEvent(this.event.BeforeNavigate,{url:event.url,target:this.getTab(win)});}},_onPageLoad:function(event){var doc=event.originalTarget;if(doc instanceof HTMLDocument){var win=doc.defaultView;var e={url:doc.URL||'',title:doc.title||'',target:this.getTab(win)};if(!doc.defaultView.frameElement){this.fireEvent(this.event.DocumentComplete,e);}
e.window=win;this.fireEvent('DOMContentLoaded',e);}},_onTabSelect:function(event){var win=gBrowser.getBrowserForTab(event.target).contentWindow
var doc=win.document;var tab=this.getTab(win);this.fireEvent(this.event.TabChanged,{url:doc.URL||'',title:doc.title||'',target:tab,tabId:tab.getId()});},_onTabOpen:function(event){var tab=this.getTab(gBrowser.getBrowserForTab(event.target).contentWindow);this.fireEvent(this.event.TabCreated,{target:tab,tabId:tab.getId()});},_onTabClose:function(event){this.fireEvent(this.event.TabRemoved,{tabId:this._getTabId(gBrowser.getBrowserForTab(event.target).contentWindow)});},_getTabId:function(win){var propertyName="KangoTabId_"+kango.getExtensionInfo().id;return win[propertyName]=win[propertyName]||this._generateTabId();},getTabBrowsers:function(){return[gBrowser];},getTabs:function(tabbrowser){var result=[];var tabContainer=tabbrowser.tabContainer;for(var i=0;i<tabContainer.childNodes.length;i++){result.push(kango.browser.getTab(gBrowser.getBrowserForTab(tabContainer.childNodes[i]).contentWindow));}
return result;},getTab:function(win){return new kango.BrowserTab(win,this._getTabId(win));},getName:function(){return'firefox';},tabs:{getAll:function(callback){var result=[];var tabBrowsers=kango.browser.getTabBrowsers();for(var i=0;i<tabBrowsers.length;i++){result=result.concat(kango.browser.getTabs(tabBrowsers[i]))}
callback(result);},getCurrent:function(callback){kango.browser.windows.getCurrent(function(win){win.getCurrentTab(function(tab){callback(tab);});});},create:function(details){var focused=typeof details.focused=='undefined'||details.focused;var reuse=typeof details.reuse!='undefined'&&details.reuse;var tab=null;if(reuse){for(var i=0;i<gBrowser.browsers.length;i++){var currentBrowser=gBrowser.getBrowserAtIndex(i);if(currentBrowser.currentURI.spec==details.url){tab=gBrowser.tabContainer.childNodes[i];break;}}}
if(tab==null){tab=gBrowser.addTab(details.url);}
if(focused){gBrowser.selectedTab=tab;}}},windows:{getAll:function(callback){this.getCurrent(function(win){callback([win]);});},getCurrent:function(callback){callback(new kango.BrowserWindow(gBrowser));},create:function(details){window.open(details.url);}},getTabProxyForWindow:function(win){var proxyName="KangoTabProxy_"+kango.getExtensionInfo().id;if(typeof win[proxyName]=='undefined'){win[proxyName]=new kango.TabProxy(this.getTab(win));}
return win[proxyName];}});kango.BrowserWindow=function(tabbrowser){this._tabbrowser=tabbrowser;};kango.BrowserWindow.prototype=kango.oop.extend(kango.IBrowserWindow,{_tabbrowser:null,getTabs:function(callback){callback(kango.browser.getTabs(this._tabbrowser));},getCurrentTab:function(callback){var tabContainer=this._tabbrowser.tabContainer;var tab=null;for(var i=0;i<tabContainer.childNodes.length;i++){tab=tabContainer.childNodes[i];if(tab.selected){break;}}
callback(kango.browser.getTab(gBrowser.getBrowserForTab(tab).contentWindow));},isActive:function(){return true;}});kango.BrowserTab=function(win,id){this._win=win;this._id=id;this._tab=this._getTabFromWindow(win);};kango.BrowserTab.prototype=kango.oop.extend(kango.IBrowserTab,{_tab:null,_id:null,_win:null,_getTabFromWindow:function(win){var targetBrowserIndex=gBrowser.getBrowserIndexForDocument(win.top.document);if(targetBrowserIndex!=-1){return gBrowser.tabContainer.childNodes[targetBrowserIndex];}
return null},getId:function(){return this._id;},getUrl:function(){var url='';try{url=this.getDOMWindow().document.URL||'';}
catch(e){}
return url;},getTitle:function(){var title='';try{title=this.getDOMWindow().document.title;}
catch(e){}
return title;},getDOMWindow:function(){return this._win.wrappedJSObject;},isActive:function(){return this._tab.selected;},navigate:function(url){gBrowser.getBrowserForTab(this._tab).setAttribute('src',url);},dispatchMessage:function(name,data){var event={name:name,data:data,origin:'tab',source:kango,target:kango};kango.browser.getTabProxyForWindow(this._win).fireEvent('message',event);}});kango.browser=new kango.Browser();